import {
    cibGithub,
    cibStackOverflow,
    cibCcMastercard,
    cibCcVisa,
    cibPaypal,
} from '@coreui/icons'
import {
    cifUs,
    cifFi,
} from '@coreui/icons'
import {
    cilArrowRight,
    cilBan,
    cilBell,
    cilCalendar,
    cilChartPie,
    cilCheck,
    cilChevronBottom,
    cilChevronTop,
    cilCheckCircle,
    cilCommentSquare,
    cilCursor,
    cilDrop,
    cilEuro,
    cilHeart,
    cilInfo,
    cilLayers,
    cilList,
    cilLocationPin,
    cilLockLocked,
    cilMagnifyingGlass,
    cilOptions,
    cilPencil,
    cilPeople,
    cilReload,
    cilSettings,
    cilSpeedometer,
    cilStar,
    cilTask,
    cilUser,
    cilUserFollow,
    cilXCircle

} from '@coreui/icons'

export const iconsSet = Object.assign(
    {},
    {
        cilArrowRight,
        cilBan,
        cilBell,
        cilCalendar,
        cilChartPie,
        cilCheck,
        cilChevronBottom,
        cilChevronTop,
        cilCheckCircle,
        cilCommentSquare,
        cilCursor,
        cilDrop,
        cilEuro,
        cilHeart,
        cilInfo,
        cilLayers,
        cilList,
        cilLocationPin,
        cilLockLocked,
        cilMagnifyingGlass,
        cilOptions,
        cilPencil,
        cilPeople,
        cilReload,
        cilSettings,
        cilSpeedometer,
        cilStar,
        cilTask,
        cilUser,
        cilUserFollow,
        cilXCircle
    },
    {
        cifUs,
        cifFi,
    },
    {
        cibGithub,
        cibStackOverflow,
        cibCcMastercard,
        cibCcVisa,
        cibPaypal,
    }
);
